# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171208_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='mission',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end date'),
            preserve_default=False,
        ),
    ]
