# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171208_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_administrator', 'Can view administrator'), ('edit_administrator', 'Can edit administrator'), ('delete_administrator', 'Can delete administrator'), ('view_teacher', 'Can view teacher'), ('edit_teacher', 'Can edit teacher'), ('delete_teacher', 'Can delete teacher'), ('view_student', 'Can view student'), ('edit_student', 'Can edit student'), ('delete_student', 'Can delete student'))},
        ),
    ]
