# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171209_0353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentoringrelationship',
            options={'permissions': (('view_mentoringrelationship', 'Can view mentoring relationship'),)},
        ),
    ]
