# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171209_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='title',
            field=models.TextField(default='title', max_length=100),
            preserve_default=False,
        ),
    ]
