# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_mission_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
