# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171210_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='content',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
