# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171210_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringrecord',
            name='student_record',
        ),
        migrations.RemoveField(
            model_name='mentoringrecord',
            name='teacher_record',
        ),
        migrations.AddField(
            model_name='mentoringrecord',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mentoringrecord',
            name='mentoring_time',
            field=models.TimeField(choices=[(datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30')]),
        ),
    ]
