# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20171213_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoringrelationship',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
