# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_mentoringrelationship_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringrelationship',
            name='active',
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='relationship_status',
            field=models.CharField(choices=[('辅导中', '辅导中'), ('辅导完成', '辅导完成')], default='辅导中', max_length=16),
        ),
    ]
