# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20171214_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringrelationship',
            name='comment',
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='administrator_comment',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='score',
            field=models.CharField(choices=[('五颗星', '五颗星'), ('四颗星', '四颗星'), ('三颗星', '三颗星'), ('两颗星', '两颗星'), ('一颗星', '一颗星')], default='五颗星', max_length=16),
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='teacher_comment',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
