# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20171218_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoringrelationship',
            name='score',
            field=models.CharField(choices=[('未评分', '未评分'), ('五颗星', '五颗星'), ('四颗星', '四颗星'), ('三颗星', '三颗星'), ('两颗星', '两颗星'), ('一颗星', '一颗星')], default='未评分', max_length=16),
        ),
    ]
