# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20171218_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoringrelationship',
            name='score',
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='student_comment',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='student_score',
            field=models.IntegerField(choices=[(-1, '未评分'), (5, '五颗星'), (4, '四颗星'), (3, '三颗星'), (2, '两颗星'), (1, '一颗星')], default=-1),
        ),
        migrations.AddField(
            model_name='mentoringrelationship',
            name='teacher_score',
            field=models.IntegerField(choices=[(-1, '未评分'), (5, '五颗星'), (4, '四颗星'), (3, '三颗星'), (2, '两颗星'), (1, '一颗星')], default=-1),
        ),
    ]
