# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20171219_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applycollege',
            options={'permissions': (('view_applycollege', 'Can view apply college'),)},
        ),
    ]
