# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20171219_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applystate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='applyschool',
            name='state',
        ),
        migrations.AddField(
            model_name='applyschool',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplyCountry'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ApplyState',
        ),
    ]
