# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20171220_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycollege',
            name='content',
        ),
        migrations.RemoveField(
            model_name='applycollege',
            name='school',
        ),
        migrations.RemoveField(
            model_name='applymajor',
            name='college',
        ),
        migrations.RemoveField(
            model_name='applymajor',
            name='content',
        ),
        migrations.RemoveField(
            model_name='applyschool',
            name='content',
        ),
        migrations.RemoveField(
            model_name='applyschool',
            name='country',
        ),
    ]
