# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20171220_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_type', models.CharField(choices=[('本科生', '本科生'), ('硕士生', '硕士生'), ('博士生', '博士生')], default='本科生', max_length=16)),
                ('usnews_rank', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('toefl', models.IntegerField(default=0)),
                ('ielts', models.FloatField(default=0)),
                ('gre', models.IntegerField(default=0)),
                ('gre_subject', models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Literature in English', 'Literature in English'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Psychology', 'Psychology')], default='Biology', max_length=128)),
                ('tuition', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('semester', models.CharField(choices=[('春季', '春季'), ('夏季', '夏季'), ('秋季', '秋季'), ('冬季', '冬季')], default='春季', max_length=8)),
                ('comment', models.TextField(default='', max_length=5000)),
                ('profession', models.TextField(default='', max_length=5000)),
                ('links', models.TextField(default='', max_length=5000)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplyCollege')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplyCountry')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplyMajor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ApplySchool')),
            ],
            options={
                'permissions': (('view_applydegree', 'Can view apply degree'),),
            },
        ),
        migrations.RemoveField(
            model_name='applybachelor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='applymaster',
            name='major',
        ),
        migrations.RemoveField(
            model_name='applyphd',
            name='major',
        ),
        migrations.DeleteModel(
            name='ApplyBachelor',
        ),
        migrations.DeleteModel(
            name='ApplyMaster',
        ),
        migrations.DeleteModel(
            name='ApplyPhD',
        ),
    ]
