# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20171222_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydegree',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='applydegree',
            name='links',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='applydegree',
            name='profession',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
