# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20171222_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applydegree',
            old_name='college',
            new_name='apply_college',
        ),
        migrations.RenameField(
            model_name='applydegree',
            old_name='country',
            new_name='apply_country',
        ),
        migrations.RenameField(
            model_name='applydegree',
            old_name='major',
            new_name='apply_major',
        ),
        migrations.RenameField(
            model_name='applydegree',
            old_name='school',
            new_name='apply_school',
        ),
    ]
