# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20171222_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applydegree',
            old_name='semester',
            new_name='apply_semester',
        ),
    ]
