# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20171222_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applydegree',
            old_name='comment',
            new_name='apply_comment',
        ),
        migrations.RenameField(
            model_name='applydegree',
            old_name='links',
            new_name='apply_link',
        ),
        migrations.RenameField(
            model_name='applydegree',
            old_name='profession',
            new_name='apply_profession',
        ),
    ]
