# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20171225_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydegree',
            name='gre_subject',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.ApplyGRESubject'),
        ),
    ]
