# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20171225_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydegree',
            name='gmat',
            field=models.IntegerField(default=0),
        ),
    ]
