# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_applydegree_gmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydegree',
            name='gmat_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applydegree',
            name='gpa_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applydegree',
            name='gre_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applydegree',
            name='ielts_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applydegree',
            name='toefl_required',
            field=models.BooleanField(default=False),
        ),
    ]
