# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20171226_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydegree',
            name='apply_course',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
    ]
