# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_applydegree_apply_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydegree',
            name='gmat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='applydegree',
            name='gre',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='applydegree',
            name='toefl',
            field=models.FloatField(default=0),
        ),
    ]
