# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_applydegreetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='applydegree',
            name='apply_degree_type',
            field=models.ManyToManyField(to='dashboard.ApplyDegreeType'),
        ),
    ]
