# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_applydegree_apply_degree_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applydegree',
            name='apply_type',
        ),
    ]
