# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20171229_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycollege',
            name='apply_major',
            field=models.ManyToManyField(to='dashboard.ApplyMajor'),
        ),
        migrations.AddField(
            model_name='applycountry',
            name='apply_school',
            field=models.ManyToManyField(to='dashboard.ApplySchool'),
        ),
        migrations.AddField(
            model_name='applyschool',
            name='apply_college',
            field=models.ManyToManyField(to='dashboard.ApplyCollege'),
        ),
    ]
