# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20171229_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycollege',
            name='apply_major',
            field=models.ManyToManyField(blank=True, to='dashboard.ApplyMajor'),
        ),
        migrations.AlterField(
            model_name='applycountry',
            name='apply_school',
            field=models.ManyToManyField(blank=True, to='dashboard.ApplySchool'),
        ),
        migrations.AlterField(
            model_name='applyschool',
            name='apply_college',
            field=models.ManyToManyField(blank=True, to='dashboard.ApplyCollege'),
        ),
    ]
