# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_auto_20171229_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymajor',
            name='apply_degree_type',
            field=models.ManyToManyField(blank=True, to='dashboard.ApplyDegreeType'),
        ),
    ]
