# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_applymajor_apply_degree_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycollege',
            name='apply_major',
        ),
        migrations.RemoveField(
            model_name='applycountry',
            name='apply_school',
        ),
        migrations.RemoveField(
            model_name='applymajor',
            name='apply_degree_type',
        ),
        migrations.RemoveField(
            model_name='applyschool',
            name='apply_college',
        ),
    ]
