# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 10:08
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_auto_20171230_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydegree',
            name='apply_curriculum',
            field=markdownx.models.MarkdownxField(blank=True, default='', max_length=5000),
        ),
    ]
