# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_remove_userprofile_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chinese_name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
