# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_userprofile_chinese_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_administrator', 'Can view administrator'), ('add_administrator', 'Can add administrator'), ('change_administrator', 'Can change administrator'), ('delete_administrator', 'Can delete administrator'), ('view_channel', 'Can view channel'), ('add_channel', 'Can add channel'), ('change_channel', 'Can change channel'), ('delete_channel', 'Can delete channel'), ('view_teacher', 'Can view teacher'), ('add_teacher', 'Can add teacher'), ('change_teacher', 'Can change teacher'), ('delete_teacher', 'Can delete teacher'), ('view_student', 'Can view student'), ('add_student', 'Can add student'), ('change_student', 'Can change student'), ('delete_student', 'Can delete student'))},
        ),
    ]
