# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_auto_20180609_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
